/**
 * Print-only blocks for detail pages.
 *
 * These render clean metadata headers and correction footers that only
 * appear when the page is printed (or saved as PDF). They are hidden
 * on screen to avoid duplication with the interactive UI.
 */

interface PrintHeaderProps {
  title: string;
  version: number;
  status: string;
  dates: string;
  /** Additional lines to show below the main metadata (e.g. legal status) */
  extraLines?: string[];
}

export function PrintHeader({ title, version, status, dates, extraLines }: PrintHeaderProps) {
  return (
    <div className="hidden print:block mb-6">
      <div className="border-b border-charcoal/30 pb-4 mb-4">
        <h1 className="font-serif text-2xl font-bold text-ink mb-1">
          {title}
        </h1>
        <p className="font-mono text-xs text-charcoal/60">
          Version {version} · {status} · {dates}
        </p>
        {extraLines && extraLines.length > 0 && (
          <div className="mt-2 space-y-0.5">
            {extraLines.map((line, i) => (
              <p key={i} className="font-mono text-xs text-charcoal/60">{line}</p>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

interface PrintFooterProps {
  /** Canonical URL path, e.g. "/evidence/some-slug" */
  canonicalPath: string;
  /** Optional additional lines */
  extraLines?: string[];
}

export function PrintFooter({ canonicalPath, extraLines }: PrintFooterProps) {
  return (
    <div className="hidden print:block mt-8 pt-4 border-t border-charcoal/30 text-xs text-charcoal/50 space-y-1 print-footer">
      <p>
        Generated by Accountability Atlas — accountabilityatlas.org{canonicalPath}
      </p>
      <p>
        Corrections and updates: accountabilityatlas.org/corrections
      </p>
      <p>
        Methodology: accountabilityatlas.org/methodology
      </p>
      {extraLines && extraLines.length > 0 && (
        extraLines.map((line, i) => (
          <p key={i}>{line}</p>
        ))
      )}
    </div>
  );
}
